language: python
python:
 - "3.3"
 - "3.4"

env:
  matrix:
   - DJANGO="Django<1.9"

services:
  - postgresql

addons:
  postgresql: "9.3"

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-dev python-pip python-lxml libcairo2 libpango1.0-0 libgdk-pixbuf2.0-0 libffi-dev shared-mime-info
install:
  - pip install -r requirements/local.txt
  - pip install python-coveralls
  - pip install coverage

before_script:
  - psql -c "CREATE ROLE db_user 'password' CREATEDB CREATEROLE REPLICATION SUPERUSER;"
  - psql -c "CREATE DATABASE my_db;"
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE my_db TO db_user;"

script:
  - python manage.py check
  - python manage.py migrate --noinput
  - coverage run --source='.' manage.py test crm_core
  - coverage report
after_success:
  - coveralls
